/* Classroom Starters — Content Banks (loaded before main script) */

const RHETORIC_QUOTE_BANK = [
  { id: 'rhet-01', quote: 'The wind whispered through the ancient pines.', device: 'Personification', hint: 'Giving human qualities to non-human things.', definition: 'Personification attributes human actions or feelings to objects or nature.' },
  { id: 'rhet-02', quote: 'The thunder grumbled angrily overhead.', device: 'Personification', hint: 'Nature given human emotion.', definition: 'Personification gives human emotions or actions to non-human things.' },
  { id: 'rhet-03', quote: 'Opportunity knocked at her door.', device: 'Personification', hint: 'An abstract idea acts like a person.', definition: 'Personification treats an abstract concept as if it can perform human actions.' },
  { id: 'rhet-04', quote: 'The sun smiled down on the playground.', device: 'Personification', hint: 'The sun is given a human expression.', definition: 'Personification gives human qualities to natural elements.' },
  { id: 'rhet-05', quote: 'Peter Piper picked a peck of pickled peppers.', device: 'Alliteration', hint: 'Repeated starting consonant sounds.', definition: 'Alliteration repeats the same initial consonant sound in nearby words.' },
  { id: 'rhet-06', quote: 'Sally sells seashells by the seashore.', device: 'Alliteration', hint: 'Notice the repeated "s" sound.', definition: 'Alliteration repeats the same initial consonant sound in nearby words.' },
  { id: 'rhet-07', quote: 'Busy bees buzzed by the blossoms.', device: 'Alliteration', hint: 'The letter "b" starts many words here.', definition: 'Alliteration repeats the same initial consonant sound in nearby words.' },
  { id: 'rhet-08', quote: 'Crisp crackers crunched in the quiet cafeteria.', device: 'Alliteration', hint: 'Repeated "cr" consonant blend.', definition: 'Alliteration repeats the same initial consonant sound in nearby words.' },
  { id: 'rhet-09', quote: 'I have told you a million times!', device: 'Hyperbole', hint: 'Extreme exaggeration for effect.', definition: 'Hyperbole uses deliberate exaggeration that is not meant literally.' },
  { id: 'rhet-10', quote: 'This backpack weighs a ton.', device: 'Hyperbole', hint: 'The weight is exaggerated beyond reality.', definition: 'Hyperbole uses deliberate exaggeration that is not meant literally.' },
  { id: 'rhet-11', quote: 'I am so hungry I could eat a horse.', device: 'Hyperbole', hint: 'An impossible amount is suggested.', definition: 'Hyperbole uses deliberate exaggeration that is not meant literally.' },
  { id: 'rhet-12', quote: 'We waited forever for the bus.', device: 'Hyperbole', hint: '"Forever" stretches time beyond truth.', definition: 'Hyperbole uses deliberate exaggeration that is not meant literally.' },
  { id: 'rhet-13', quote: 'The bees buzzed and the clock ticked.', device: 'Onomatopoeia', hint: 'Words that imitate sounds.', definition: 'Onomatopoeia uses words that phonetically resemble the sounds they describe.' },
  { id: 'rhet-14', quote: 'The fire crackled and the water splashed.', device: 'Onomatopoeia', hint: 'Sound words mimic real noises.', definition: 'Onomatopoeia uses words that phonetically resemble the sounds they describe.' },
  { id: 'rhet-15', quote: 'The door slammed and the floor creaked.', device: 'Onomatopoeia', hint: 'Listen for words that sound like actions.', definition: 'Onomatopoeia uses words that phonetically resemble the sounds they describe.' },
  { id: 'rhet-16', quote: 'Pop! The balloon burst in the hallway.', device: 'Onomatopoeia', hint: '"Pop" imitates a sudden sound.', definition: 'Onomatopoeia uses words that phonetically resemble the sounds they describe.' },
  { id: 'rhet-17', quote: 'It was a deafening silence in the room.', device: 'Oxymoron', hint: 'Two opposite ideas placed together.', definition: 'An oxymoron combines contradictory terms to create a striking effect.' },
  { id: 'rhet-18', quote: 'The teacher called it an open secret.', device: 'Oxymoron', hint: 'Can a secret be open?', definition: 'An oxymoron combines contradictory terms to create a striking effect.' },
  { id: 'rhet-19', quote: 'That student is seriously funny.', device: 'Oxymoron', hint: 'Serious and funny oppose each other.', definition: 'An oxymoron combines contradictory terms to create a striking effect.' },
  { id: 'rhet-20', quote: 'It was a bittersweet farewell at graduation.', device: 'Oxymoron', hint: 'Bitter and sweet are opposites.', definition: 'An oxymoron combines contradictory terms to create a striking effect.' },
  { id: 'rhet-21', quote: 'Her smile was sunshine on a rainy day.', device: 'Metaphor', hint: 'A direct comparison without like or as.', definition: 'A metaphor states one thing is another to show a shared quality.' },
  { id: 'rhet-22', quote: 'The classroom was a zoo after lunch.', device: 'Metaphor', hint: 'Comparing two unlike things directly.', definition: 'A metaphor states one thing is another to show a shared quality.' },
  { id: 'rhet-23', quote: 'Life is a highway with many exits.', device: 'Metaphor', hint: 'Life is compared to a road.', definition: 'A metaphor states one thing is another to show a shared quality.' },
  { id: 'rhet-24', quote: 'Time is money, so use it wisely.', device: 'Metaphor', hint: 'Time is equated with something valuable.', definition: 'A metaphor states one thing is another to show a shared quality.' },
  { id: 'rhet-25', quote: 'He ran like the wind across the oval.', device: 'Simile', hint: 'Uses "like" to compare.', definition: 'A simile compares two things using like or as.' },
  { id: 'rhet-26', quote: 'Her voice was as sharp as a blade.', device: 'Simile', hint: 'Uses "as" to compare.', definition: 'A simile compares two things using like or as.' },
  { id: 'rhet-27', quote: 'The snow was like a soft white blanket.', device: 'Simile', hint: 'Snow is compared using "like".', definition: 'A simile compares two things using like or as.' },
  { id: 'rhet-28', quote: 'As busy as a bee, she finished every task.', device: 'Simile', hint: 'A common comparison with "as".', definition: 'A simile compares two things using like or as.' },
  { id: 'rhet-29', quote: 'The light of the fire is a sight.', device: 'Assonance', hint: 'Repeated vowel sounds in nearby words.', definition: 'Assonance repeats vowel sounds within nearby words.' },
  { id: 'rhet-30', quote: 'Hear the mellow wedding bells.', device: 'Assonance', hint: 'Listen for repeated "e" sounds.', definition: 'Assonance repeats vowel sounds within nearby words.' },
  { id: 'rhet-31', quote: 'Go and mow the lawn.', device: 'Assonance', hint: 'The "o" sound repeats.', definition: 'Assonance repeats vowel sounds within nearby words.' },
  { id: 'rhet-32', quote: 'The rain in Spain falls mainly on the plain.', device: 'Assonance', hint: 'Repeated long "a" vowel sounds.', definition: 'Assonance repeats vowel sounds within nearby words.' },
  { id: 'rhet-33', quote: 'We will fight, we will win, we will never give up.', device: 'Repetition', hint: 'A phrase is repeated for emphasis.', definition: 'Repetition repeats words or phrases to emphasise an idea.' },
  { id: 'rhet-34', quote: 'Alone, alone, all alone on a wide, wide sea.', device: 'Repetition', hint: 'Key words appear again and again.', definition: 'Repetition repeats words or phrases to emphasise an idea.' },
  { id: 'rhet-35', quote: 'Real rats, real problems, real solutions.', device: 'Repetition', hint: 'The word "real" is repeated.', definition: 'Repetition repeats words or phrases to emphasise an idea.' },
  { id: 'rhet-36', quote: 'Never, never, never give in.', device: 'Repetition', hint: 'One word is hammered home.', definition: 'Repetition repeats words or phrases to emphasise an idea.' },
  { id: 'rhet-37', quote: 'The fire station burned down last night.', device: 'Irony', hint: 'The outcome is the opposite of what you expect.', definition: 'Irony occurs when reality contradicts what is expected.' },
  { id: 'rhet-38', quote: 'The pilot was afraid of heights.', device: 'Irony', hint: 'A pilot should not fear flying.', definition: 'Irony occurs when reality contradicts what is expected.' },
  { id: 'rhet-39', quote: 'A writing teacher handed in a blank report.', device: 'Irony', hint: 'The expert fails at their own skill.', definition: 'Irony occurs when reality contradicts what is expected.' },
  { id: 'rhet-40', quote: 'The lifeguard who could not swim saved no one.', device: 'Irony', hint: 'The rescuer lacks the needed ability.', definition: 'Irony occurs when reality contradicts what is expected.' },
  { id: 'rhet-41', quote: 'The river danced over the rocks.', device: 'Personification', hint: 'Water is given a human action.', definition: 'Personification attributes human actions or feelings to objects or nature.' },
  { id: 'rhet-42', quote: 'Bang! Clang! The pots crashed in the kitchen.', device: 'Onomatopoeia', hint: 'Words mimic metallic sounds.', definition: 'Onomatopoeia uses words that phonetically resemble the sounds they describe.' },
];

const ETYMOLOGY_ROOT_BANK = [
  { id: 'root-01', root: 'CHRON', meaning: 'time', words: [
    { text: 'Chronological', correct: true, breakdown: 'Chron (time) + logical → in time order' },
    { text: 'Spectator', correct: false, breakdown: 'Spect (look) — not related to time' },
    { text: 'Synchronize', correct: true, breakdown: 'Syn (together) + chron (time) → at the same time' },
    { text: 'Geography', correct: false, breakdown: 'Geo (earth) + graph (write) — about places' },
  ]},
  { id: 'root-02', root: 'GEO', meaning: 'earth', words: [
    { text: 'Geography', correct: true, breakdown: 'Geo (earth) + graph (write) → describing Earth' },
    { text: 'Chronicle', correct: false, breakdown: 'Chron (time) — a record of events' },
    { text: 'Geology', correct: true, breakdown: 'Geo (earth) + logy (study) → study of Earth' },
    { text: 'Spectacle', correct: false, breakdown: 'Spect (look) — something impressive to see' },
  ]},
  { id: 'root-03', root: 'SPECT', meaning: 'look / see', words: [
    { text: 'Spectator', correct: true, breakdown: 'Spect (look) + ator (one who) → one who watches' },
    { text: 'Chronometer', correct: false, breakdown: 'Chron (time) — a precise timekeeper' },
    { text: 'Spectacle', correct: true, breakdown: 'Spect (look) + acle → something worth seeing' },
    { text: 'Geothermal', correct: false, breakdown: 'Geo (earth) + thermal (heat)' },
  ]},
  { id: 'root-04', root: 'GRAPH', meaning: 'write / draw', words: [
    { text: 'Autograph', correct: true, breakdown: 'Auto (self) + graph (write) → self-written signature' },
    { text: 'Telephone', correct: false, breakdown: 'Tele (far) + phone (sound)' },
    { text: 'Biography', correct: true, breakdown: 'Bio (life) + graph (write) → written life story' },
    { text: 'Thermometer', correct: false, breakdown: 'Thermo (heat) + meter (measure)' },
  ]},
  { id: 'root-05', root: 'BIO', meaning: 'life', words: [
    { text: 'Biology', correct: true, breakdown: 'Bio (life) + logy (study) → study of living things' },
    { text: 'Geology', correct: false, breakdown: 'Geo (earth) — study of rocks' },
    { text: 'Biography', correct: true, breakdown: 'Bio (life) + graph (write) → life story' },
    { text: 'Chronology', correct: false, breakdown: 'Chron (time) — timeline of events' },
  ]},
  { id: 'root-06', root: 'TELE', meaning: 'far / distant', words: [
    { text: 'Telescope', correct: true, breakdown: 'Tele (far) + scope (see) → see far away' },
    { text: 'Microscope', correct: false, breakdown: 'Micro (small) + scope (see)' },
    { text: 'Television', correct: true, breakdown: 'Tele (far) + vision (see) → see from afar' },
    { text: 'Autograph', correct: false, breakdown: 'Auto (self) + graph (write)' },
  ]},
  { id: 'root-07', root: 'PHON', meaning: 'sound / voice', words: [
    { text: 'Telephone', correct: true, breakdown: 'Tele (far) + phone (sound) → sound from far away' },
    { text: 'Photograph', correct: false, breakdown: 'Photo (light) + graph (write)' },
    { text: 'Symphony', correct: true, breakdown: 'Sym (together) + phon (sound) → sounds together' },
    { text: 'Hydrophobic', correct: false, breakdown: 'Hydro (water) + phob (fear)' },
  ]},
  { id: 'root-08', root: 'THERM', meaning: 'heat', words: [
    { text: 'Thermometer', correct: true, breakdown: 'Thermo (heat) + meter (measure) → measures heat' },
    { text: 'Geothermal', correct: true, breakdown: 'Geo (earth) + thermal (heat) → Earth heat' },
    { text: 'Chronology', correct: false, breakdown: 'Chron (time) — order of events' },
    { text: 'Portable', correct: false, breakdown: 'Port (carry) — able to be carried' },
  ]},
  { id: 'root-09', root: 'HYDRO', meaning: 'water', words: [
    { text: 'Hydrate', correct: true, breakdown: 'Hydro (water) → add water' },
    { text: 'Hydrophobic', correct: true, breakdown: 'Hydro (water) + phob (fear) → water-fearing' },
    { text: 'Autobiography', correct: false, breakdown: 'Auto (self) + bio (life) + graph (write)' },
    { text: 'Luminous', correct: false, breakdown: 'Lum (light) — giving off light' },
  ]},
  { id: 'root-10', root: 'MICRO', meaning: 'small', words: [
    { text: 'Microscope', correct: true, breakdown: 'Micro (small) + scope (see) → see small things' },
    { text: 'Microorganism', correct: true, breakdown: 'Micro (small) + organism → tiny living thing' },
    { text: 'Telescope', correct: false, breakdown: 'Tele (far) + scope (see)' },
    { text: 'Transport', correct: false, breakdown: 'Trans (across) + port (carry)' },
  ]},
  { id: 'root-11', root: 'AUTO', meaning: 'self', words: [
    { text: 'Autograph', correct: true, breakdown: 'Auto (self) + graph (write) → self-written' },
    { text: 'Autobiography', correct: true, breakdown: 'Auto (self) + bio (life) + graph (write)' },
    { text: 'Antibiotic', correct: false, breakdown: 'Anti (against) + bio (life)' },
    { text: 'Sublime', correct: false, breakdown: 'Sub (under) + lim (threshold)' },
  ]},
  { id: 'root-12', root: 'ANTI', meaning: 'against', words: [
    { text: 'Antibiotic', correct: true, breakdown: 'Anti (against) + bio (life) → against bacteria' },
    { text: 'Antifreeze', correct: true, breakdown: 'Anti (against) + freeze → prevents freezing' },
    { text: 'Automatic', correct: false, breakdown: 'Auto (self) — acting by itself' },
    { text: 'Prehistoric', correct: false, breakdown: 'Pre (before) + historic (history)' },
  ]},
  { id: 'root-13', root: 'PRE', meaning: 'before', words: [
    { text: 'Preview', correct: true, breakdown: 'Pre (before) + view (see) → see beforehand' },
    { text: 'Prehistoric', correct: true, breakdown: 'Pre (before) + historic → before recorded history' },
    { text: 'Postscript', correct: false, breakdown: 'Post (after) + script (write)' },
    { text: 'Transport', correct: false, breakdown: 'Trans (across) + port (carry)' },
  ]},
  { id: 'root-14', root: 'SUB', meaning: 'under / below', words: [
    { text: 'Submarine', correct: true, breakdown: 'Sub (under) + marine (sea) → under the sea' },
    { text: 'Subway', correct: true, breakdown: 'Sub (under) + way (path) → path under ground' },
    { text: 'Supervise', correct: false, breakdown: 'Super (above) + vis (see)' },
    { text: 'Portable', correct: false, breakdown: 'Port (carry) — able to be carried' },
  ]},
  { id: 'root-15', root: 'TRANS', meaning: 'across / beyond', words: [
    { text: 'Transport', correct: true, breakdown: 'Trans (across) + port (carry) → carry across' },
    { text: 'Translate', correct: true, breakdown: 'Trans (across) + late (carry) → carry meaning across' },
    { text: 'Subtract', correct: false, breakdown: 'Sub (under) + tract (pull)' },
    { text: 'Audible', correct: false, breakdown: 'Aud (hear) — able to be heard' },
  ]},
  { id: 'root-16', root: 'PORT', meaning: 'carry', words: [
    { text: 'Portable', correct: true, breakdown: 'Port (carry) + able → able to be carried' },
    { text: 'Transport', correct: true, breakdown: 'Trans (across) + port (carry) → carry across' },
    { text: 'Import', correct: true, breakdown: 'Im (in) + port (carry) → carry in' },
    { text: 'Luminous', correct: false, breakdown: 'Lum (light) — giving off light' },
  ]},
  { id: 'root-17', root: 'VOC', meaning: 'call / voice', words: [
    { text: 'Vocabulary', correct: true, breakdown: 'Voc (voice/word) + ulary → collection of words' },
    { text: 'Vocal', correct: true, breakdown: 'Voc (voice) + al → relating to the voice' },
    { text: 'Audible', correct: false, breakdown: 'Aud (hear) — able to be heard' },
    { text: 'Philosophy', correct: false, breakdown: 'Phil (love) + soph (wisdom)' },
  ]},
  { id: 'root-18', root: 'AUD', meaning: 'hear', words: [
    { text: 'Audience', correct: true, breakdown: 'Aud (hear) + ience → those who listen' },
    { text: 'Audible', correct: true, breakdown: 'Aud (hear) + ible → able to be heard' },
    { text: 'Vocal', correct: false, breakdown: 'Voc (voice) — relating to the voice' },
    { text: 'Pathology', correct: false, breakdown: 'Path (disease) + logy (study)' },
  ]},
  { id: 'root-19', root: 'LUM', meaning: 'light', words: [
    { text: 'Luminous', correct: true, breakdown: 'Lum (light) + ous → giving off light' },
    { text: 'Illuminate', correct: true, breakdown: 'In (into) + lumin (light) + ate → light up' },
    { text: 'Hydrophobic', correct: false, breakdown: 'Hydro (water) + phob (fear)' },
    { text: 'Chronicle', correct: false, breakdown: 'Chron (time) — record of events' },
  ]},
  { id: 'root-20', root: 'PATH', meaning: 'feeling / disease', words: [
    { text: 'Sympathy', correct: true, breakdown: 'Sym (together) + path (feeling) → shared feeling' },
    { text: 'Pathology', correct: true, breakdown: 'Path (disease) + logy (study) → study of disease' },
    { text: 'Philosophy', correct: false, breakdown: 'Phil (love) + soph (wisdom)' },
    { text: 'Geography', correct: false, breakdown: 'Geo (earth) + graph (write)' },
  ]},
  { id: 'root-21', root: 'PHIL', meaning: 'love', words: [
    { text: 'Philosophy', correct: true, breakdown: 'Phil (love) + soph (wisdom) → love of wisdom' },
    { text: 'Philanthropy', correct: true, breakdown: 'Phil (love) + anthro (human) → love of humanity' },
    { text: 'Phonograph', correct: false, breakdown: 'Phon (sound) + graph (write)' },
    { text: 'Antifreeze', correct: false, breakdown: 'Anti (against) + freeze' },
  ]},
  { id: 'root-22', root: 'LOG', meaning: 'word / study / reason', words: [
    { text: 'Biology', correct: true, breakdown: 'Bio (life) + logy (study) → study of life' },
    { text: 'Geology', correct: true, breakdown: 'Geo (earth) + logy (study) → study of Earth' },
    { text: 'Autograph', correct: false, breakdown: 'Auto (self) + graph (write)' },
    { text: 'Telescope', correct: false, breakdown: 'Tele (far) + scope (see)' },
  ]},
];

const VARIABLE_SCENARIO_BANK = [
  { id: 'var-01', scenario: 'Mia tests whether plant growth changes when using salt water instead of fresh water. She keeps the same type of plant, pot size, and sunlight for each trial.', iv: 'Type of water (salt vs fresh)', dv: 'Plant growth (height)', controlled: ['Same plant species', 'Same pot size', 'Same sunlight'] },
  { id: 'var-02', scenario: 'Jay measures how far a toy car travels when launched from different ramp heights. He uses the same car and surface each time.', iv: 'Ramp height', dv: 'Distance the car travels', controlled: ['Same toy car', 'Same surface', 'Same launch method'] },
  { id: 'var-03', scenario: 'A class investigates whether bean seeds germinate faster in warm or cool cupboards. They use identical seeds and equal water.', iv: 'Cupboard temperature', dv: 'Germination speed', controlled: ['Same seed type', 'Equal water', 'Same containers'] },
  { id: 'var-04', scenario: 'Sam tests which brand of paper towel absorbs the most water. He uses the same amount of water and identical beakers.', iv: 'Paper towel brand', dv: 'Amount of water absorbed', controlled: ['Same water volume', 'Same beakers', 'Same testing method'] },
  { id: 'var-05', scenario: 'At the Victorian Schools Science Fair, Priya compares how quickly ice cubes melt on black and white paper under identical lamps.', iv: 'Paper colour (black vs white)', dv: 'Time for ice to melt', controlled: ['Same lamp distance', 'Same ice cube size', 'Same room temperature'] },
  { id: 'var-06', scenario: 'Ethan investigates whether vinegar or water dissolves eggshell faster. He uses equal volumes and identical eggshell pieces.', iv: 'Liquid type (vinegar vs water)', dv: 'Time for eggshell to dissolve', controlled: ['Same liquid volume', 'Same eggshell size', 'Same container'] },
  { id: 'var-07', scenario: 'A Year 8 team tests if fertiliser affects the height of wheat seedlings over two weeks. All pots receive the same light and water.', iv: 'Amount of fertiliser', dv: 'Seedling height after two weeks', controlled: ['Same light hours', 'Same water amount', 'Same soil type'] },
  { id: 'var-08', scenario: 'Lily measures heart rate before and after different exercise types, keeping rest time and measurement method the same.', iv: 'Type of exercise', dv: 'Heart rate (beats per minute)', controlled: ['Same rest period', 'Same measurement tool', 'Same time of day'] },
  { id: 'var-09', scenario: 'A Melbourne classroom tests which roof colour keeps a model house coolest under a heat lamp.', iv: 'Roof colour', dv: 'Internal temperature of model house', controlled: ['Same lamp wattage', 'Same distance from lamp', 'Same model size'] },
  { id: 'var-10', scenario: 'Noah compares how far a ball bounces on carpet versus timber flooring, using the same ball and drop height.', iv: 'Floor surface type', dv: 'Bounce height', controlled: ['Same ball', 'Same drop height', 'Same release method'] },
  { id: 'var-11', scenario: 'Students test whether the number of rubber bands on a paddle-pop stick catapult changes how far a projectile flies.', iv: 'Number of rubber bands', dv: 'Projectile distance', controlled: ['Same stick length', 'Same projectile mass', 'Same launch angle'] },
  { id: 'var-12', scenario: 'A regional science fair entry tests if compost or potting mix produces taller tomato plants over four weeks.', iv: 'Soil type (compost vs potting mix)', dv: 'Tomato plant height', controlled: ['Same seed variety', 'Same water schedule', 'Same pot size'] },
  { id: 'var-13', scenario: 'Chloe investigates whether stirring affects how quickly sugar dissolves in warm water, using identical cups and sugar amounts.', iv: 'Stirring (yes vs no)', dv: 'Time for sugar to dissolve', controlled: ['Same water temperature', 'Same sugar mass', 'Same cup size'] },
  { id: 'var-14', scenario: 'A Ballarat school tests which insulation material keeps water warmest for longest in identical flasks.', iv: 'Insulation material', dv: 'Water temperature after 30 minutes', controlled: ['Same starting temperature', 'Same water volume', 'Same flask type'] },
  { id: 'var-15', scenario: 'Oscar measures whether the length of a pendulum string changes the number of swings in one minute.', iv: 'Pendulum string length', dv: 'Number of swings per minute', controlled: ['Same bob mass', 'Same release angle', 'Same attachment height'] },
  { id: 'var-16', scenario: 'A Geelong team compares mould growth on bread kept in sealed versus open containers at the same temperature.', iv: 'Container type (sealed vs open)', dv: 'Area of mould growth', controlled: ['Same bread type', 'Same temperature', 'Same observation period'] },
  { id: 'var-17', scenario: 'Zara tests whether the angle of a solar panel changes the voltage produced under identical sunlight conditions.', iv: 'Panel angle', dv: 'Voltage produced', controlled: ['Same panel size', 'Same light intensity', 'Same meter'] },
  { id: 'var-18', scenario: 'Students investigate if the type of music played affects how quickly a pet mouse completes a maze, keeping food reward and maze design constant.', iv: 'Type of music', dv: 'Time to complete maze', controlled: ['Same maze design', 'Same food reward', 'Same time of testing'] },
  { id: 'var-19', scenario: 'A Bendigo inquiry tests whether adding salt changes the density at which an egg floats in water.', iv: 'Salt concentration', dv: 'Whether the egg floats', controlled: ['Same egg', 'Same water volume', 'Same container'] },
  { id: 'var-20', scenario: 'Hannah compares evaporation rates from wide and narrow containers holding the same volume of water in the same location.', iv: 'Container width', dv: 'Volume of water evaporated per day', controlled: ['Same water volume', 'Same location', 'Same temperature'] },
  { id: 'var-21', scenario: 'A Warrnambool science project tests which wind turbine blade shape generates the most electricity from a desk fan.', iv: 'Blade shape', dv: 'Electricity generated (millivolts)', controlled: ['Same fan speed', 'Same turbine distance', 'Same testing duration'] },
  { id: 'var-22', scenario: 'Leo investigates whether the thickness of wire affects the brightness of a bulb in a simple circuit with the same battery.', iv: 'Wire thickness', dv: 'Bulb brightness', controlled: ['Same battery', 'Same bulb type', 'Same circuit length'] },
];

const FOOD_WEB_BANK = [
  { id: 'web-01', organisms: [
    { name: 'Eucalyptus leaf', role: 0 }, { name: 'Grasshopper', role: 1 },
    { name: 'Blue-tongued lizard', role: 2 }, { name: 'Wedge-tailed eagle', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-02', organisms: [
    { name: 'Seagrass', role: 0 }, { name: 'Sea urchin', role: 1 },
    { name: 'Snapper fish', role: 2 }, { name: 'Great white shark', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-03', organisms: [
    { name: 'Acacia leaves', role: 0 }, { name: 'Kangaroo', role: 1 },
    { name: 'Dingo', role: 2 }, { name: 'Saltwater crocodile', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-04', organisms: [
    { name: 'Phytoplankton', role: 0 }, { name: 'Krill', role: 1 },
    { name: 'Adelie penguin', role: 2 }, { name: 'Leopard seal', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-05', organisms: [
    { name: 'Grass', role: 0 }, { name: 'Zebra', role: 1 },
    { name: 'Lion', role: 2 }, { name: 'Vulture', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-06', organisms: [
    { name: 'Mangrove leaves', role: 0 }, { name: 'Mud crab', role: 1 },
    { name: 'Barramundi', role: 2 }, { name: 'Estuarine crocodile', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-07', organisms: [
    { name: 'Spinifex grass', role: 0 }, { name: 'Bilby', role: 1 },
    { name: 'Brown snake', role: 2 }, { name: 'Wedge-tailed eagle', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-08', organisms: [
    { name: 'Kelp', role: 0 }, { name: 'Sea urchin', role: 1 },
    { name: 'Sea otter', role: 2 }, { name: 'Orca', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-09', organisms: [
    { name: 'Coral algae', role: 0 }, { name: 'Parrotfish', role: 1 },
    { name: 'Grouper', role: 2 }, { name: 'Reef shark', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-10', organisms: [
    { name: 'Lichen', role: 0 }, { name: 'Caribou', role: 1 },
    { name: 'Arctic fox', role: 2 }, { name: 'Polar bear', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-11', organisms: [
    { name: 'Fig tree leaves', role: 0 }, { name: 'Possum', role: 1 },
    { name: 'Powerful owl', role: 2 }, { name: 'Dingo', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-12', organisms: [
    { name: 'River algae', role: 0 }, { name: 'Murray cod fingerling', role: 1 },
    { name: 'Murray cod', role: 2 }, { name: 'Pelican', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-13', organisms: [
    { name: 'Rainforest fern', role: 0 }, { name: 'Tree kangaroo', role: 1 },
    { name: 'Python', role: 2 }, { name: 'Cassowary', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
  { id: 'web-14', organisms: [
    { name: 'Bamboo', role: 0 }, { name: 'Giant panda', role: 1 },
    { name: 'Snow leopard', role: 2 }, { name: 'Tiger', role: 3 },
  ], roles: ['Producer', 'Primary Consumer', 'Secondary Consumer', 'Apex Predator'] },
];

const SOURCE_ITEM_BANK = [
  { id: 'src-01', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: "A soldier's diary entry from Gallipoli, 1915", answer: 'A', prompt: 'Primary sources are firsthand accounts created at the time of an event.', feedbackCorrect: 'Correct — a diary written during the event is a primary source.', feedbackWrong: 'This is a primary source — it was created by someone who experienced the event firsthand.' },
  { id: 'src-02', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A 2020 textbook chapter about the Gallipoli campaign', answer: 'B', prompt: 'Secondary sources analyse or interpret events after they occurred.', feedbackCorrect: 'Correct — a textbook interprets past events using other sources.', feedbackWrong: 'This is a secondary source — it was created later to explain and analyse the event.' },
  { id: 'src-03', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A photograph of the 1901 Federation ceremony', answer: 'A', prompt: 'Photographs taken at the time are primary evidence.', feedbackCorrect: 'Correct — an original photograph from the event is a primary source.', feedbackWrong: 'This photograph was taken at the time — it is a primary source.' },
  { id: 'src-04', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A documentary made in 2015 about the Eureka Stockade', answer: 'B', prompt: 'Secondary sources are created after the event to interpret it.', feedbackCorrect: 'Correct — a documentary made long after the event is a secondary source.', feedbackWrong: 'This is a secondary source — it interprets the past using other evidence.' },
  { id: 'src-05', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A letter written by a gold miner during the 1850s Victorian gold rush', answer: 'A', prompt: 'Letters written at the time are firsthand evidence.', feedbackCorrect: 'Correct — a contemporary letter is a primary source.', feedbackWrong: 'This letter was written at the time — it is a primary source.' },
  { id: 'src-06', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'An encyclopaedia article about Captain James Cook', answer: 'B', prompt: 'Encyclopaedias summarise and interpret existing research.', feedbackCorrect: 'Correct — an encyclopaedia article is a secondary source.', feedbackWrong: 'This is a secondary source — it was compiled after the events to explain them.' },
  { id: 'src-07', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A government poster recruiting soldiers for World War I', answer: 'A', prompt: 'Original artefacts from the time period are primary sources.', feedbackCorrect: 'Correct — a contemporary recruitment poster is a primary source.', feedbackWrong: 'This poster was created at the time — it is a primary source.' },
  { id: 'src-08', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A historian\'s book published in 2018 about the Stolen Generations', answer: 'B', prompt: 'Books written by historians long after events are secondary sources.', feedbackCorrect: 'Correct — the historian interprets evidence from the past.', feedbackWrong: 'This is a secondary source — it analyses events using other sources.' },
  { id: 'src-09', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'An Aboriginal bark painting created before European settlement', answer: 'A', prompt: 'Cultural artefacts from the time are primary evidence.', feedbackCorrect: 'Correct — an original artwork from the period is a primary source.', feedbackWrong: 'This artwork was created at the time — it is a primary source.' },
  { id: 'src-10', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A Year 9 student\'s essay about Ned Kelly', answer: 'B', prompt: 'Student essays written today interpret past events.', feedbackCorrect: 'Correct — a modern essay is a secondary source.', feedbackWrong: 'This is a secondary source — it was written long after Ned Kelly\'s life.' },
  { id: 'src-11', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A newspaper report from 1942 about the bombing of Darwin', answer: 'A', prompt: 'Newspapers published at the time of an event are primary sources.', feedbackCorrect: 'Correct — a contemporary newspaper report is a primary source.', feedbackWrong: 'This report was published at the time — it is a primary source.' },
  { id: 'src-12', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A museum display label explaining Aboriginal tools', answer: 'B', prompt: 'Modern museum labels interpret artefacts for visitors.', feedbackCorrect: 'Correct — the label explains and interprets the past.', feedbackWrong: 'This is a secondary source — it was written to explain historical objects.' },
  { id: 'src-13', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A petition signed by women demanding the vote in 1891', answer: 'A', prompt: 'Original documents from a campaign are primary evidence.', feedbackCorrect: 'Correct — the petition is an original document from the time.', feedbackWrong: 'This petition was created during the campaign — it is a primary source.' },
  { id: 'src-14', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A podcast episode reviewing the Mabo decision', answer: 'B', prompt: 'Modern media that discusses past events is secondary.', feedbackCorrect: 'Correct — the podcast reviews and interprets a historical event.', feedbackWrong: 'This is a secondary source — it discusses the past from a modern perspective.' },
  { id: 'src-15', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Australia has six states and two mainland territories.', answer: 'A', prompt: 'Facts can be verified with evidence; opinions express beliefs or judgments.', feedbackCorrect: 'Correct — this can be verified with official geographic data.', feedbackWrong: 'This is a fact — it can be checked and proven true.' },
  { id: 'src-16', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'The Eureka Stockade was the most important event in Australian history.', answer: 'B', prompt: 'Words like "most important" signal a personal judgment.', feedbackCorrect: 'Correct — "most important" is a value judgment, not a verifiable fact.', feedbackWrong: 'This is an opinion — importance is subjective and debatable.' },
  { id: 'src-17', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'The First Fleet arrived in 1788.', answer: 'A', prompt: 'Historical dates supported by records are facts.', feedbackCorrect: 'Correct — the arrival date is documented historical fact.', feedbackWrong: 'This is a fact — the date is recorded in historical records.' },
  { id: 'src-18', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Australian rules football is the best sport in the world.', answer: 'B', prompt: '"Best" expresses a personal preference.', feedbackCorrect: 'Correct — "best" is a subjective opinion, not a verifiable fact.', feedbackWrong: 'This is an opinion — people can disagree about what is "best".' },
  { id: 'src-19', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'The Australian Constitution was enacted in 1901.', answer: 'A', prompt: 'Official enactment dates can be verified in records.', feedbackCorrect: 'Correct — this date is documented in legal records.', feedbackWrong: 'This is a fact — the date can be verified officially.' },
  { id: 'src-20', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Life was miserable for everyone on the goldfields.', answer: 'B', prompt: 'Generalisations about how people felt are opinions.', feedbackCorrect: 'Correct — "miserable for everyone" is a sweeping judgment.', feedbackWrong: 'This is an opinion — not everyone experienced the goldfields the same way.' },
  { id: 'src-21', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Uluru is located in the Northern Territory.', answer: 'A', prompt: 'Geographic locations can be verified on maps.', feedbackCorrect: 'Correct — Uluru\'s location is a verifiable geographic fact.', feedbackWrong: 'This is a fact — it can be confirmed on official maps.' },
  { id: 'src-22', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Prime Minister Robert Menzies was a better leader than Gough Whitlam.', answer: 'B', prompt: 'Comparing leaders involves personal judgment.', feedbackCorrect: 'Correct — "better leader" is a value judgment.', feedbackWrong: 'This is an opinion — leadership quality is debated, not proven.' },
  { id: 'src-23', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Approximately 60,000 Australians died in World War I.', answer: 'A', prompt: 'Casualty figures supported by records are facts.', feedbackCorrect: 'Correct — this figure is based on historical records.', feedbackWrong: 'This is a fact — the number is documented in war records.' },
  { id: 'src-24', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'The Sydney Harbour Bridge is ugly.', answer: 'B', prompt: 'Describing something as "ugly" is a personal view.', feedbackCorrect: 'Correct — beauty is subjective, not a verifiable fact.', feedbackWrong: 'This is an opinion — people can disagree about appearance.' },
  { id: 'src-25', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Women gained the federal vote in Australia in 1902.', answer: 'A', prompt: 'Legislative dates are documented facts.', feedbackCorrect: 'Correct — this date is recorded in Australian law.', feedbackWrong: 'This is a fact — the year can be verified in legal history.' },
  { id: 'src-26', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Colonisation brought only progress to Australia.', answer: 'B', prompt: '"Only progress" is a one-sided judgment.', feedbackCorrect: 'Correct — this sweeping claim is an opinion, not a proven fact.', feedbackWrong: 'This is an opinion — historians debate the impacts of colonisation.' },
  { id: 'src-27', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'The Mabo decision was handed down by the High Court in 1992.', answer: 'A', prompt: 'Court decision dates are verifiable legal facts.', feedbackCorrect: 'Correct — the year of the decision is a documented fact.', feedbackWrong: 'This is a fact — the date is recorded in legal history.' },
  { id: 'src-28', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Anzac Day is the most meaningful public holiday in Australia.', answer: 'B', prompt: '"Most meaningful" expresses a personal value.', feedbackCorrect: 'Correct — meaningfulness is subjective and debatable.', feedbackWrong: 'This is an opinion — people value different holidays for different reasons.' },
  { id: 'src-29', mode: 'source', modeLabel: 'Primary vs Secondary Source', optionA: 'Primary Source', optionB: 'Secondary Source', text: 'A convict\'s record from the Port Arthur penal settlement', answer: 'A', prompt: 'Official records created at the time are primary sources.', feedbackCorrect: 'Correct — a contemporary official record is a primary source.', feedbackWrong: 'This record was created at the time — it is a primary source.' },
  { id: 'src-30', mode: 'fact', modeLabel: 'Fact vs Opinion', optionA: 'Fact', optionB: 'Opinion', text: 'Canberra became the national capital in 1913.', answer: 'A', prompt: 'Official designation dates are verifiable facts.', feedbackCorrect: 'Correct — this date is documented in Australian history.', feedbackWrong: 'This is a fact — the year can be confirmed in official records.' },
];

const CLASSIFIER_THEME_BANK = [
  {
    id: 'physical-chemical',
    instruction: 'Sort each change as Physical or Chemical.',
    labelA: 'Physical Change',
    labelB: 'Chemical Change',
    poolA: ['Crushing a can', 'Melting ice', 'Dissolving sugar', 'Boiling water', 'Shredding paper', 'Chopping wood', 'Freezing juice', 'Breaking glass', 'Condensing steam', 'Bending wire', 'Tearing fabric', 'Grinding pepper', 'Evaporating alcohol'],
    poolB: ['Rusting iron', 'Baking a cake', 'Burning wood', 'Digesting food', 'Fireworks exploding', 'Milk turning sour', 'Cooking an egg', 'Rotting fruit', 'Vinegar and baking soda reaction', 'Bleaching hair', 'Photosynthesis in leaves', 'Fermenting bread dough', 'Tarnishing silver'],
  },
  {
    id: 'living-nonliving',
    instruction: 'Classify each item as Living or Non-Living.',
    labelA: 'Living',
    labelB: 'Non-Living',
    poolA: ['Eucalyptus tree', 'Magpie', 'Bacteria', 'Mushroom', 'Earthworm', 'Kangaroo', 'Algae', 'Moss', 'Blue gum seedling', 'Yeast cell', 'Coral polyp', 'Fern frond', 'Platypus'],
    poolB: ['Granite rock', 'River water', 'Oxygen gas', 'Sunlight', 'Plastic bottle', 'Cloud', 'Salt crystal', 'Sand', 'Steel beam', 'Carbon dioxide', 'Glass window', 'Copper coin', 'Wind'],
  },
  {
    id: 'renewable-energy',
    instruction: 'Sort each energy source as Renewable or Non-Renewable.',
    labelA: 'Renewable Energy',
    labelB: 'Non-Renewable Energy',
    poolA: ['Solar power', 'Wind turbines', 'Hydroelectric dam', 'Geothermal heat', 'Biomass energy', 'Wave power', 'Tidal energy', 'Solar hot water', 'Bagasse power', 'Hydrogen fuel cell (green)', 'Pumped hydro storage', 'Landfill gas capture'],
    poolB: ['Coal plant', 'Crude oil', 'Natural gas', 'Uranium nuclear fuel', 'Diesel fuel', 'Petrol engine', 'Brown coal', 'Peat burning', 'Liquefied petroleum gas', 'Oil shale', 'Tar sands', 'Kerosene lamp'],
  },
  {
    id: 'conductors-insulators',
    instruction: 'Classify each material as a Conductor or Insulator.',
    labelA: 'Conductor',
    labelB: 'Insulator',
    poolA: ['Copper wire', 'Iron nail', 'Aluminium foil', 'Saltwater', 'Gold ring', 'Graphite pencil lead', 'Steel spoon', 'Mercury liquid', 'Brass key', 'Silver coin', 'Zinc strip', 'Tap water'],
    poolB: ['Rubber tire', 'Plastic ruler', 'Wooden spoon', 'Glass bottle', 'Pure wool', 'Dry air', 'Ceramic mug', 'Styrofoam cup', 'Diamond', 'Distilled water', 'Cotton glove', 'Nylon rope'],
  },
  {
    id: 'metals-nonmetals',
    instruction: 'Sort each element as a Metal or Non-Metal.',
    labelA: 'Metal',
    labelB: 'Non-Metal',
    poolA: ['Gold (Au)', 'Iron (Fe)', 'Copper (Cu)', 'Aluminium (Al)', 'Silver (Ag)', 'Magnesium (Mg)', 'Zinc (Zn)', 'Lead (Pb)', 'Tin (Sn)', 'Nickel (Ni)', 'Platinum (Pt)', 'Sodium (Na)'],
    poolB: ['Carbon (C)', 'Oxygen (O)', 'Helium (He)', 'Sulfur (S)', 'Nitrogen (N)', 'Chlorine (Cl)', 'Hydrogen (H)', 'Phosphorus (P)', 'Iodine (I)', 'Neon (Ne)', 'Fluorine (F)', 'Silicon (Si)'],
  },
  {
    id: 'contact-forces',
    instruction: 'Classify each force as Contact or Non-Contact.',
    labelA: 'Contact Force',
    labelB: 'Non-Contact Force',
    poolA: ['Friction on tires', 'Air resistance on parachute', 'Tension in rope', 'Normal kick force', 'Buoyancy in water', 'Muscular push on door', 'Drag on swimmer', 'Elastic force in spring', 'Applied force on box', 'Reaction force on ground', 'Compression in cushion', 'Viscous drag in honey'],
    poolB: ['Gravity pulling an apple', 'Magnetic attraction', 'Electrostatic hair cling', "Earth's magnetic field", 'Gravitational pull of Moon', 'Nuclear strong force', 'Electric field on charge', 'Gravitational force on satellite', 'Magnetic repulsion of poles', 'Weight force on book', 'Electrostatic repulsion', 'Gravitational attraction between planets'],
  },
  {
    id: 'acids-bases',
    instruction: 'Sort each substance as an Acid or Base / Alkali.',
    labelA: 'Acid',
    labelB: 'Base / Alkali',
    poolA: ['Lemon juice', 'Vinegar', 'Battery acid', 'Stomach acid', 'Coffee', 'Tomatoes', 'Orange juice', 'Cola drink', 'Gastric juice', 'Hydrochloric acid', 'Citric acid', 'Sour milk'],
    poolB: ['Soap', 'Bleach', 'Baking soda', 'Toothpaste', 'Ammonia cleaner', 'Drain cleaner', 'Antacid tablet', 'Milk of magnesia', 'Oven cleaner', 'Washing soda', 'Lime water', 'Caustic soda solution'],
  },
  {
    id: 'herbivores-carnivores',
    instruction: 'Classify each animal as a Primary Consumer (Herbivore) or Secondary Consumer (Carnivore).',
    labelA: 'Primary Consumer (Herbivore)',
    labelB: 'Secondary Consumer (Carnivore)',
    poolA: ['Koala', 'Possum', 'Caterpillar', 'Grasshopper', 'Wallaby', 'Rabbit', 'Kangaroo', 'Galapagos tortoise', 'Deer', 'Cow', 'Sheep', 'Brushtail possum', 'Emu'],
    poolB: ['Wedge-tailed eagle', 'Dingo', 'Kookaburra', 'Blue-tongued lizard', 'Tiger snake', 'Fox', 'Owl', 'Hawk', 'Wolf', 'Crocodile', 'Shark', 'Spider', 'Frog'],
  },
];
